server:
  port: 3010

spring:
  application:
    name: lojavirtual

  datasource:
    url: jdbc:postgresql://localhost:5432/estudos_db?currentSchema=lojavirtual_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  url:
    base: "http://localhost:3010"
    pedido: "/detalhe-compra/"



